[package]
name = "athena-dap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
anyhow.workspace = true
libc.workspace = true
async-channel.workspace = true
tracing.workspace = true
