[package]
name = "athena-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ropey.workspace = true
tree-sitter.workspace = true
tree-sitter-go.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-javascript.workspace = true
streaming-iterator.workspace = true
anyhow.workspace = true
gpui.workspace = true
athena-ui.workspace = true
